///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Res {
  Res._();

  //========================== Api Endpoints  ===============================
  static const apiLogin = 'auth/login';
  static const apiRegister = 'auth/register';
  static const apiChangePassword = 'auth/change-password';
  static const apiFinancial = 'auth/financial-transaction';

  static const apiAboutUs = 'pages/about';
  static const apiFaq = 'pages/faq';
  static const apiContact = 'pages/contact';
  static const apiTerms = 'pages/terms-conditions';


  static const apiProfile = 'api2/trade/GetPortfolio';
  static const apiRealTimePrices = 'api2/Prices';
  static const apiBuy = 'api2/trade/create';
  static const apiSell = 'api2/trade/fifoclose';


  //========================== Font  ===============================

  //todo here change app font name
  // static const appEnFontName = 'Julee';
  static const appEnFontName = 'Roboto';

  static const appArFontName = 'ArefRuqaa';
  // static const appArFontName = 'Cairo';

  //========================== Animation Assets  ===============================
  static const String animApiLoading = 'assets/anim/loading.json';
  static const String animApiEmpty = 'assets/anim/api_empty.json';
  static const String animApiError = 'assets/anim/api_error.json';
  static const String animDelivery = 'assets/anim/delivery.json';
  static const String animEmptyCart = 'assets/anim/empty_cart.json';
  static const String animSuccess = 'assets/anim/success.json';
  static const String animDisconnect = 'assets/anim/disconnect.json';

  static const String animCoinsFalling = 'assets/anim/coins.json';

  //========================== Icons Assets  ===============================
  static const String iconPerson = 'assets/icons/person.svg';
  static const String iconAboutUs = 'assets/icons/about_us.svg';
  static const String iconContactUs = 'assets/icons/contact_us.svg';
  static const String iconHome = 'assets/icons/home.svg';
  static const String iconLogOut = 'assets/icons/logout.svg';
  static const String iconNotifications = 'assets/icons/notifications.svg';
  static const String iconPassword = 'assets/icons/password.svg';
  static const String iconOrderHistory = 'assets/icons/order_history.svg';
  static const String iconPrivacy = 'assets/icons/privacy.svg';
  static const String iconTerms = 'assets/icons/terms.svg';
  static const String iconProfile = 'assets/icons/profile.svg';
  static const String iconQuestions = 'assets/icons/questions.svg';
  static const String iconServices = 'assets/icons/services.svg';
  static const String iconLanguage = 'assets/icons/language.svg';
  static const String iconBuy = 'assets/icons/buy.svg';
  static const String iconFinancial = 'assets/icons/financial.svg';
  static const String iconSell = 'assets/icons/sell.svg';
  static const String iconWithdrawGold = 'assets/icons/withdraw_gold.svg';
  static const String iconWithdrawCash = 'assets/icons/withdraw_cash.svg';

  static const String iconAssignTo = 'assets/icons/assign_to.svg';
  static const String iconEdit = 'assets/icons/edit.svg';
  static const String iconIndoorMeeting = 'assets/icons/indoor_meeting.svg';
  static const String iconCall = 'assets/icons/call.svg';
  static const String iconWhatsapp = 'assets/icons/whatsapp.svg';
  static const String iconAddActivity = 'assets/icons/add_activity.svg';
  static const String iconMore = 'assets/icons/more.svg';
  static const String iconEmail = 'assets/icons/email.svg';
  static const String iconDelete = 'assets/icons/delete.svg';
  static const String iconGifts = 'assets/icons/gift.svg';
  static const String iconOffers = 'assets/icons/offers.svg';
  static const String iconUsdFlag = 'assets/icons/usd_flag.svg';
  static const String iconEuroFlag = 'assets/icons/euro_flag.svg';
  static const String iconEgpFlag = 'assets/icons/egp_flag.svg';
  static const String iconUpload = 'assets/icons/upload.svg';

  //========================== Images Assets  ===============================

  static const imageSplash = "assets/images/splash_bg.jpg";
  static const facebookImage = "assets/images/social/facebook.png";
  static const instagramImage = "assets/images/social/instagram.png";
  static const twitterImage = "assets/images/social/twitter.png";
  static const imageLogo = "assets/images/launcher/logo_transparent.png";
  static const imageProfileUser = "assets/images/profile_user.png";
  static const imageNotFound = "assets/images/not_found.jpg";
}
